version: '3'
services:
  web:
    container_name: bishop-brain
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - './ssl:/etc/nginx/cert'
